name: Weekly Update

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Force use PAT so that push back will trigger push action working.
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - name: modify readme if necessary
        run: |
          releases="$(curl -s https://api.github.com/repos/aliyun/aliyun-cli/releases)"
          latest_tag="$(echo "${releases}" | jq -r '.[0].tag_name')"
          latest_html_url="$(echo "${releases}" | jq -r '.[0].html_url')"
          docker_tag="${latest_tag#v}"

          if [ -z "$(git --no-pager tag -l "${latest_tag}")" ]; then
            sed -i "/^## Supported tags/a \\\n- [${docker_tag}](${latest_html_url})" README.md
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "chore: add new tag" || true
            git tag -f "${latest_tag}"
          fi
      - name: Push changes
        if: github.event_name == 'push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          tags: true
          force: true
