name: Docker Build

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  DOCKER_REPOSITORY: abcfy2/docker-cli

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: calc docker tag
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            DOCKER_TAG=latest
          else
            DOCKER_TAG="${GITHUB_REF_NAME#v}"
          fi
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          build-args: |
            ALIYUN_CLI_VERSION=${{ env.DOCKER_TAG }}
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_TAG }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repository: ${{ env.DOCKER_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}
