name: Docker Build

on: [push]

env:
  DOCKER_REPOSITORY: abcfy2/aliyun-cli

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: calc docker tag
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            DOCKER_TAG=latest
          else
            DOCKER_TAG="${GITHUB_REF_NAME#v}"
          fi
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64/v8
          build-args: |
            ALIYUN_CLI_VERSION=${{ env.DOCKER_TAG }}
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}
