name: Docker Build

on: [push]

env:
  DOCKER_REPOSITORY: ${{ github.repository_owner }}/aliyun-cli
  GHCR_REPOSITORY: ghcr.io/${{ github.repository_owner }}/aliyun-cli
  QUAY_IO_REPOSITORY: quay.io/${{ github.repository_owner }}/aliyun-cli

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REPOSITORY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: calc docker tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            DOCKER_TAG=latest
          else
            DOCKER_TAG="${GITHUB_REF_NAME#v}"
          fi
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64/v8
          build-args: |
            ALIYUN_CLI_VERSION=${{ env.DOCKER_TAG }}
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_TAG }},${{ env.GHCR_REPOSITORY }}:${{ env.DOCKER_TAG }},${{ env.QUAY_IO_REPOSITORY }}:${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        if: ${{ github.ref_name == 'main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}
